# -*- coding: utf-8 -*-
"""SimpleT5_News-Summary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qz8l7obxcQEZ-WPhIQLB849W1vekvMmK

See also: https://huggingface.co/docs/transformers/main/model_doc/t5

## Load Libraries
"""

!pip install simplet5

import pandas as pd
from sklearn.model_selection import train_test_split
from simplet5 import SimpleT5

"""## Load Data"""

def getSampleData():
  path = "https://raw.githubusercontent.com/Shivanandroy/T5-Finetuning-PyTorch/main/data/news_summary.csv"
  df = pd.read_csv(path)

  # simpleT5 expects dataframe to have 2 columns: "source_text" and "target_text"
  df = df.rename(columns={"headlines":"target_text", "text":"source_text"})
  df = df[['source_text', 'target_text']]

  # T5 model expects a task related prefix: since it is a summarization task, we will add a prefix "summarize: "
  df['source_text'] = "summarize: " + df['source_text']
  return df

df = getSampleData()

"""## Split Data"""

train_df, test_df = train_test_split(df, test_size=0.2)

"""## Create Model"""

model = SimpleT5()
model.from_pretrained(model_type="t5", model_name="t5-base")
model.train(train_df=train_df,
            eval_df=test_df,
            source_max_token_len=128,
            target_max_token_len=50,
            batch_size=8, max_epochs=3, use_gpu=True)

model.load_model("t5","outputs/epoch-2", use_gpu=True)

text_to_summarize="""summarize:
Lawyers for Alexey Navalny said Monday they have lost contact with the jailed Russian opposition leader, who was believed to be imprisoned in a penal colony about 150 miles east of Moscow, and his whereabouts are unknown.

Navalny was sentenced to 19 years in prison in August, after he was found guilty of creating an extremist community, financing extremist activities and numerous other crimes. He was already serving sentences of 11-and-a-half years in a maximum security facility on fraud and other charges he denies.

Supporters of Navalny claim his arrest and incarceration are a politically motivated attempt to stifle his criticism of Russian President Vladimir Putin.
"""
model.predict(text_to_summarize)

"""## Onyx"""

#model.convert_and_load_onnx_model(model_dir="outputs/SimpleT5-epoch-2-train-loss-0.9526")
#model.onnx_predict(text_to_summarize)